allowBuilds:
  esbuild: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - '@triggerix-ai/component'
  - '@triggerix/core'
  - '@types/node'
  - '@triggerix/runtime'

shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - nanoid
